version: '3'

# Compose file for Influxdb, NodeRed, Grafana  
services:
  influxdb:
    image: influxdb:2.6.1
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=univ-lorawan
      - DOCKER_INFLUXDB_INIT_ORG=training-usmb
      - DOCKER_INFLUXDB_INIT_BUCKET=iot-platform
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=U3lsdmFpbk1vbnRhZ255RXN0VW5DaGFtcGlvbl9Gb3JtYXRpb25Mb1JhV0FOX1VuaXZfU2F2b2llXzIwMjMhCg==
      - TZ=Europe/Paris
      #DOCKER_INFLUXDB_INIT_RETENTION=1w
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influx_data:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    
  nodered:
    build: ./node_build
    container_name: nodered
    #image: nodered/node-red:2.2.3-12
    volumes:
     - ./node_data:/data
    ports:
      - "1880:1880"      
  
  grafana:
    user: "1000"
    image: grafana/grafana-oss:9.4.3
    volumes:
      - ./grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=lorawan  
       
       
        #  telegraf:
        #image: telegraf:1.25-alpine
        #environment:
        # - #INFLUX_TOKEN=Rm9ybWF0aW9uTG9SYVdBTlVuaXZTTUIyMDIzRm9ybWF0aW9uTG9SYVdBTlVuaXZTTUIyMDIzRm9ybWF0aW9uCg==
        #- TZ=Europe/Paris
        #depends_on:
        #- influxdb
        #volumes:
      # Mount for telegraf config
      #- ./telegraf_data:/etc/telegraf:ro

